version: "3.8"

services:
  geometra-db:
    image: postgres:14
    container_name: test-db
    restart: no
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
